[package]
name = "async-exercises"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "dining-philosophers-async"
path = "dining-philosophers.rs"

[dependencies]
tokio = { version = "1.36.0", features = ["full"] }
