[package]
name = "microcontroller-example"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-m-rt = "0.7.0"
embedded-hal = "0.2.6"
gd32f1x0-hal = { version = "0.7.1", features = ["rt", "gd32f130x8"] }
panic-halt = "0.2.0"
