name: Lint
permissions:
  contents: read

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Clippy
        run: cargo clippy -- -Dwarnings

  format:
    runs-on: ubuntu-latest
    env:
      NIGHTLY_VERSION: nightly-2025-09-01
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Install formatting dependencies
        uses: ./.github/workflows/apt-get-install
        with:
          packages: gettext yapf3

      - name: Install pinned nightly for rustfmt
        run: |
          rustup toolchain install --profile minimal "$NIGHTLY_VERSION"
          rustup component add rustfmt --toolchain "$NIGHTLY_VERSION"

      - name: Check formatting
        uses: dprint/check@9cb3a2b17a8e606d37aae341e49df3654933fc23 # v2.3

  typos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Check for typos
        uses: crate-ci/typos@bee27e3a4fd1ea2111cf90ab89cd076c870fce14 # v1.48.0
        with:
          config: ./.github/typos.toml

  lockfiles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false

      - name: Setup Bazel cache
        uses: ./.github/workflows/setup-bazel-cache

      - name: Setup Rust cache
        uses: ./.github/workflows/setup-rust-cache

      - name: Check Cargo lockfile
        run: cargo update --workspace --locked

      - name: Check Bazel lockfile
        run: bazel mod deps --lockfile_mode=error
